export const words = [
  { id: 1, translated: "forehead", org: "czoło" },
  { id: 2, translated: "cheek", org: "policzek" },
  { id: 3, translated: "heel", org: "pięta" },
  { id: 4, translated: "loin", org: "lędźwie" },
  { id: 5, translated: "calf", org: "łydka" },
  { id: 6, translated: "nipple", org: "sutek" },
  { id: 7, translated: "palm", org: "wnętrze dłoni" },
  { id: 8, translated: "groin", org: "pachwina" },
  { id: 9, translated: "inguinal region", org: "obszar pachwinowy" },
  { id: 10, translated: "elbow", org: "łokieć" },
  { id: 11, translated: "big toe", org: "paluch" },
  { id: 12, translated: "leg", org: "noga" },
  { id: 13, translated: "hair", org: "włosy" },
  { id: 14, translated: "finger", org: "palec" },
  { id: 15, translated: "chin", org: "broda/podbródek" },
  { id: 16, translated: "breast", org: "pierś" },
  { id: 17, translated: "hip", org: "biodro" },
  { id: 18, translated: "neck", org: "szyja" },
  { id: 19, translated: "toe", org: "palec u nogi" },
  { id: 20, translated: "ear", org: "ucho" },
  { id: 21, translated: "jaw", org: "szczęka" },
  { id: 22, translated: "mandible", org: "żuchwa" },
  { id: 23, translated: "shin", org: "goleń" },
  { id: 24, translated: "genitals", org: "genitalia" },
  { id: 25, translated: "penis", org: "penis" },
  { id: 26, translated: "testicles", org: "jądra" },
  { id: 27, translated: "thigh", org: "udo" },
  { id: 28, translated: "hand", org: "ręka" },
  { id: 29, translated: "armpit", org: "pacha" },
  { id: 30, translated: "axilla", org: "pacha" },
  { id: 31, translated: "buttock", org: "pośladek" },
  { id: 32, translated: "nose", org: "nos" },
  { id: 33, translated: "Adam’s apple", org: "Jabłko Adama" },
  { id: 34, translated: "knee", org: "kolano" },
  { id: 35, translated: "patella/kneecap", org: "rzepka" },
  { id: 36, translated: "ankle", org: "kostka" },
  { id: 37, translated: "sole", org: "podeszwa stopy" },
  { id: 38, translated: "upper arm", org: "ramię" },
  { id: 39, translated: "forearm", org: "przedramię" },
  { id: 40, translated: "wrist", org: "nadgarstek" },
  { id: 41, translated: "thumb", org: "kciuk" },
  { id: 42, translated: "foot", org: "stopa" },
  { id: 43, translated: "chest", org: "klatka piersiowa" },
  { id: 44, translated: "thorax", org: "klatka piersiowa" },
  { id: 45, translated: "stommach/tummy/belly/abdomen", org: "brzuch" },
  { id: 46, translated: "navel/belly button/umbilicus", org: "pępek" },
  { id: 47, translated: "shoulder", org: "bark" },
  { id: 48, translated: "lower leg", org: "goleń" },
  { id: 49, translated: "lower limb", org: "dolna kończyna" },
  { id: 50, translated: "trunk", org: "tułów" },
  { id: 51, translated: "upper limb", org: "górna kończyna" },
  { id: 52, translated: "body", org: "ciało" },
  { id: 53, translated: "bone", org: "kość" },
  { id: 54, translated: "cavity", org: "jama" },
  { id: 55, translated: "cell", org: "komórka" },
  { id: 56, translated: "diaphragm", org: "przepona" },
  { id: 57, translated: "eye", org: "oko" },
  { id: 58, translated: "face", org: "twarz" },
  { id: 59, translated: "eyelash", org: "rzęsa" },
  { id: 60, translated: "eyelid", org: "powieka" },
  { id: 61, translated: "heart", org: "serce" },
  { id: 62, translated: "joint", org: "staw" },
  { id: 63, translated: "lip", org: "warga" },
  { id: 64, translated: "mouth", org: "usta" },
  { id: 65, translated: "skull", org: "czaszka" },
  { id: 66, translated: "spine", org: "kręgosłup" },
  { id: 67, translated: "tissue", org: "tkanka" },
  { id: 68, translated: "instep", org: "podbicie" },
  { id: 69, translated: "ovum", org: "komórka jajowa" },
  { id: 70, translated: "back", org: "plecy" },
  { id: 71, translated: "torso", org: "tułów" },
  { id: 72, translated: "intestine", org: "jelito" },
  { id: 73, translated: "femur", org: "kość udowa" },
  { id: 74, translated: "cranial cavity", org: "jama czaszkowa" },
  { id: 75, translated: "thoracic cavity", org: "jama klatki piersiowej" },
  {
    id: 76,
    translated: "abdominopelvic cavity",
    org: "jama brzuszno-miednicza",
  },
  { id: 77, translated: "cranium", org: "czaszka" },
  { id: 78, translated: "rib", org: "żebro" },
  { id: 79, translated: "sternum", org: "mostek" },
  { id: 80, translated: "spinal column", org: "kręgosłup" },
  { id: 81, translated: "vertebral column", org: "kręgosłup" },
  { id: 82, translated: "spine", org: "kręgosłup" },
  { id: 83, translated: "backbone", org: "kręgosłup" },
  { id: 84, translated: "oesophagus", org: "przełyk" },
  { id: 85, translated: "blood vessel", org: "naczynie krwionośne" },
  { id: 86, translated: "artery", org: "tętnica" },
  { id: 87, translated: "vein", org: "żyła" },
  { id: 88, translated: "aorta", org: "aorta" },
  { id: 89, translated: "pulmonary artery", org: "tętnica płucna" },
  { id: 90, translated: "The abdominal cavity", org: "jama brzuszna" },
  { id: 91, translated: "The pelvic cavity", org: "jama miednicy" },
  { id: 92, translated: "layer", org: "warstwa" },
  { id: 93, translated: "muscle", org: "mięsień" },
  { id: 94, translated: "fat", org: "tłuszcz" },
  { id: 95, translated: "connective tissue", org: "tkanka łączna" },
  { id: 96, translated: "organ", org: "organ" },
  { id: 97, translated: "small intestine", org: "jelito cienkie" },
  { id: 98, translated: "large intestine", org: "jelito grube" },
  { id: 99, translated: "liver", org: "wątroba" },
  { id: 100, translated: "pancreas", org: "trzustka" },
  { id: 101, translated: "spleen", org: "śledziona" },
  { id: 102, translated: "peritoneum", org: "otrzewna" },
  { id: 103, translated: "membrane", org: "błona" },
  { id: 104, translated: "urinary bladder", org: "pęcherz moczowy" },
  { id: 105, translated: "rectum", org: "odbytnica" },
  { id: 106, translated: "pelvis", org: "miednica" },
  { id: 107, translated: "feverish", org: "gorączkujący" },
  { id: 108, translated: "carpals", org: "kości nadgarstka" },
  { id: 109, translated: "clavicle", org: "obojczyk" },
  { id: 110, translated: "coccyx", org: "kość ogonowa" },
  { id: 111, translated: "fibula", org: "kość strzałkowa" },
  { id: 112, translated: "frontal", org: "czołowy" },
  { id: 113, translated: "humerus", org: "kość ramienna" },
  { id: 114, translated: "ilium", org: "kość biodrowa" },
  { id: 115, translated: "ischium", org: "kość kulszowa" },
  { id: 116, translated: "mandible", org: "żuchwa/szczęka dolna" },
  { id: 117, translated: "maxilla", org: "kość szczękowa" },
  { id: 118, translated: "metacarpals", org: "kości śródręcza" },
  { id: 119, translated: "metatarsals", org: "kości śródstopia" },
  { id: 120, translated: "occipital", org: "potylica" },
  { id: 121, translated: "parietal", org: "kość ciemieniowa" },
  { id: 122, translated: "phalanges", org: "paliczki" },
  { id: 123, translated: "pubis", org: "kość łonowa" },
  { id: 124, translated: "radius", org: "kość promieniowa" },
  { id: 125, translated: "ribs", org: "żebra" },
  { id: 126, translated: "sacrum", org: "kość krzyżowa" },
  { id: 127, translated: "scapula", org: "łopatka" },
  { id: 128, translated: "tarsals", org: "kości stępu" },
  { id: 129, translated: "tibia", org: "kość piszczelowa" },
  { id: 130, translated: "ulna", org: "kość łokciowa" },
  { id: 131, translated: "vertebra", org: "kręg" },
  { id: 132, translated: "zygomatic", org: "jarzmowy" },
  {
    id: 133,
    translated: "The Male Reproductive System",
    org: "męski układ rozrodczy",
  },
  {
    id: 134,
    translated: "The Female Reproductive System",
    org: "kobiecy układ rozrodczy",
  },
  { id: 135, translated: "The Urinary System", org: "układ moczowy" },
  { id: 136, translated: "The Respiratory System", org: "układ oddechowy" },
  { id: 137, translated: "The Lymphatic System", org: "układ limfatyczny" },
  { id: 138, translated: "The Digestive System", org: "układ pokarmowy" },
  {
    id: 139,
    translated: "The Cardiovascular System",
    org: "układ sercowo-naczyniowy",
  },
  { id: 140, translated: "The Endocrine System", org: "układ hormonalny" },
  { id: 141, translated: "The Muscular System", org: "układ mięśniowy" },
  { id: 142, translated: "The Nervous System", org: "układ nerwowy" },
  { id: 143, translated: "The Skeletal System", org: "układ szkieletowy" },
  { id: 144, translated: "The Integumentary System", org: "układ powłokowy" },
  { id: 145, translated: "affect", org: "atakować (choroba)" },
  { id: 146, translated: "bend down", org: "schylać się/zginać" },
  { id: 147, translated: "consist (of)", org: "składać się (z)" },
  { id: 148, translated: "maintain", org: "utrzymać (na tym samym poziomie)" },
  { id: 149, translated: "overdo", org: "przesadzić/przesilić się" },
  { id: 150, translated: "radiate", org: "promieniować" },
  { id: 151, translated: "stab", org: "wbić/ukłuć" },
  { id: 152, translated: "combine", org: "łączyć/mieszać" },
  { id: 153, translated: "contain", org: "zawierać" },
  { id: 154, translated: "compose", org: "tworzyć" },
  { id: 155, translated: "notice", org: "zauważać" },
  { id: 156, translated: "protect (by)", org: "chroniony (przez)" },
  { id: 157, translated: "bound (by)", org: "związane (przez)" },
  { id: 158, translated: "divide into", org: "podzielić na coś" },
  { id: 159, translated: "ovoid", org: "jajowaty" },
  { id: 160, translated: "dome-shaped", org: "kopulasty" },
  { id: 161, translated: "inner", org: "wewnętrzny" },
  { id: 162, translated: "hollow", org: "wgłębienie" },
  { id: 163, translated: "junction", org: "skrzyżowanie" },
  { id: 164, translated: "sharp", org: "ostry/przeszywający" },
  { id: 165, translated: "include", org: "zawierać" },
  { id: 166, translated: "stabbing pain", org: "przeszywający" },
  { id: 167, translated: "injury", org: "uraz" },
  { id: 168, translated: "treating", org: "udzielanie pomocy med." },
  { id: 169, translated: "sustain", org: "odnosić (obrażenia)" },
  { id: 170, translated: "laceration", org: "rana szarpana" },
  { id: 171, translated: "treatment", org: "leczenie" },
  { id: 172, translated: "require", org: "potrzebować" },
  { id: 173, translated: "abrasion", org: "otarcie skóry" },
  { id: 174, translated: "puncture", org: "punkcja" },
  { id: 175, translated: "strain", org: "nadwyrężyć" },
  { id: 176, translated: "unharmed", org: "nietknięty" },
  { id: 177, translated: "severe", org: "poważny" },
  { id: 178, translated: "trauma", org: "uraz" },
  { id: 179, translated: "complaint", org: "dolegliwość" },
  { id: 180, translated: "suspect", org: "podejrzewać" },
  { id: 181, translated: "movement", org: "ruch" },
  { id: 182, translated: "experience", org: "doświadczyć" },
  { id: 183, translated: "identify", org: "rozpoznawać" },
  { id: 184, translated: "complain", org: "narzekać/skarżyć się" },
  { id: 185, translated: "extending", org: "rozciągający" },
  { id: 186, translated: "minor", org: "drobny" },
  { id: 187, translated: "bruising", org: "stłuczenie" },
  { id: 188, translated: "significant", org: "znaczny" },
  { id: 189, translated: "fracture", org: "złamanie" },
  { id: 190, translated: "evident", org: "widoczny" },
  { id: 191, translated: "concern", org: "niepokój" },
  { id: 192, translated: "splint", org: "szyna (unieruchamiająca złamanie)" },
  { id: 193, translated: "fleshy", org: "mięsisty" },
  { id: 194, translated: "indication", org: "objaw" },
  { id: 195, translated: "immobile", org: "unieruchomiony" },
  { id: 196, translated: "proper", org: "odpowiedni" },
  { id: 197, translated: "content", org: "zawartość" },
  { id: 198, translated: "digestion", org: "trawienie" },
  { id: 199, translated: "feverish", org: "gorączkujący" },
  { id: 200, translated: "coughing", org: "kaszlenie" },
  { id: 201, translated: "weight", org: "waga" },
  { id: 202, translated: "fever", org: "gorączka" },
  { id: 203, translated: "weak", org: "słaby" },
  { id: 204, translated: "tired", org: "zmęczony" },
  { id: 205, translated: "inferiorly", org: "poniższy" },
  { id: 206, translated: "anteriorly", org: "przednio" },
  { id: 207, translated: "laterally", org: "bocznie" },
  { id: 208, translated: "food", org: "pokarm" },
  { id: 209, translated: "respiratory gases", org: "gazy oddechowe" },
  { id: 210, translated: "ingestion", org: "przyjmowanie pokarmu" },
  { id: 211, translated: "digestion", org: "trawienie" },
  { id: 212, translated: "absorption", org: "wchłanianie" },
  { id: 213, translated: "irritability", org: "drażliwość" },
  { id: 214, translated: "stimuli", org: "bodźce" },
  { id: 215, translated: "nutrition", org: "odżywianie" },
  { id: 216, translated: "reproduction", org: "reprodukcja" },
  { id: 217, translated: "propagation", org: "rozmnażanie" },
  { id: 218, translated: "species", org: "gatunek" },
  { id: 219, translated: "metabolism", org: "metabolizm" },
  { id: 220, translated: "growth", org: "wzrost/rośnięcie" },
  { id: 221, translated: "respiration", org: "oddychanie" },
  { id: 222, translated: "oxygen", org: "tlen" },
  { id: 223, translated: "intake", org: "pobór (tlenu)" },
  { id: 224, translated: "carbon dioxide", org: "dwutlenek węgla" },
  { id: 225, translated: "excretion", org: "wydalanie" },
];
