export const words = [
  { translated: "forehead", org: "czoło" },
  { translated: "cheek", org: "policzek" },
  { translated: "heel", org: "pięta" },
  { translated: "loin", org: "lędźwie" },
  { translated: "calf", org: "łydka" },
  { translated: "nipple", org: "sutek" },
  { translated: "palm", org: "wnętrze dłoni" },
  { translated: "groin", org: "pachwina" },
  { translated: "inguinal region", org: "obszar pachwinowy" },
  { translated: "elbow", org: "łokieć" },
  { translated: "big toe", org: "paluch" },
  { translated: "leg", org: "noga" },
  { translated: "hair", org: "włosy" },
  { translated: "finger", org: "palec" },
  { translated: "chin", org: "broda/podbródek" },
  { translated: "breast", org: "pierś" },
  { translated: "hip", org: "biodro" },
  { translated: "neck", org: "szyja" },
  { translated: "toe", org: "palec u nogi" },
  { translated: "ear", org: "ucho" },
  { translated: "jaw", org: "szczęka" },
  { translated: "mandible", org: "żuchwa" },
  { translated: "shin", org: "goleń" },
  { translated: "genitals", org: "genitalia" },
  { translated: "penis", org: "penis" },
  { translated: "testicles", org: "jądra" },
  { translated: "thigh", org: "udo" },
  { translated: "hand", org: "ręka" },
  { translated: "armpit", org: "pacha" },
  { translated: "axilla", org: "pacha" },
  { translated: "buttock", org: "pośladek" },
  { translated: "nose", org: "nos" },
  { translated: "Adam’s apple", org: "Jabłko Adama" },
  { translated: "knee", org: "kolano" },
  { translated: "patella/kneecap", org: "rzepka" },
  { translated: "ankle", org: "kostka" },
  { translated: "sole", org: "podeszwa stopy" },
  { translated: "upper arm", org: "ramię" },
  { translated: "forearm", org: "przedramię" },
  { translated: "wrist", org: "nadgarstek" },
  { translated: "thumb", org: "kciuk" },
  { translated: "foot", org: "stopa" },
  { translated: "chest", org: "klatka piersiowa" },
  { translated: "thorax", org: "klatka piersiowa" },
  { translated: "stommach/tummy/belly/abdomen", org: "brzuch" },
  { translated: "navel/belly button/umbilicus", org: "pępek" },
  { translated: "shoulder", org: "bark" },
  { translated: "lower leg", org: "goleń" },
  { translated: "lower limb", org: "dolna kończyna" },
  { translated: "trunk", org: "tułów" },
  { translated: "upper limb", org: "górna kończyna" },
  { translated: "body", org: "ciało" },
  { translated: "bone", org: "kość" },
  { translated: "cavity", org: "jama" },
  { translated: "cell", org: "komórka" },
  { translated: "diaphragm", org: "przepona" },
  { translated: "eye", org: "oko" },
  { translated: "face", org: "twarz" },
  { translated: "eyelash", org: "rzęsa" },
  { translated: "eyelid", org: "powieka" },
  { translated: "heart", org: "serce" },
  { translated: "joint", org: "staw" },
  { translated: "lip", org: "warga" },
  { translated: "mouth", org: "usta" },
  { translated: "skull", org: "czaszka" },
  { translated: "spine", org: "kręgosłup" },
  { translated: "tissue", org: "tkanka" },
  { translated: "instep", org: "podbicie" },
  { translated: "ovum", org: "komórka jajowa" },
  { translated: "back", org: "plecy" },
  { translated: "torso", org: "tułów" },
  { translated: "intestine", org: "jelito" },
  { translated: "femur", org: "kość udowa" },
  { translated: "cranial cavity", org: "jama czaszkowa" },
  { translated: "thoracic cavity", org: "jama klatki piersiowej" },
  { translated: "abdominopelvic cavity", org: "jama brzuszno-miednicza" },
  { translated: "cranium", org: "czaszka" },
  { translated: "rib", org: "żebro" },
  { translated: "sternum", org: "mostek" },
  { translated: "spinal column", org: "kręgosłup" },
  { translated: "vertebral column", org: "kręgosłup" },
  { translated: "spine", org: "kręgosłup" },
  { translated: "backbone", org: "kręgosłup" },
  { translated: "oesophagus", org: "przełyk" },
  { translated: "blood vessel", org: " naczynie krwionośne" },
  { translated: "artery", org: "tętnica" },
  { translated: "vein", org: "żyła" },
  { translated: "aorta", org: "aorta" },
  { translated: "pulmonary artery", org: "tętnica płucna" },
  { translated: "The abdominal cavity", org: "jama brzuszna" },
  { translated: "The pelvic cavity", org: "jama miednicy" },
  { translated: "layer", org: "warstwa" },
  { translated: "muscle", org: "mięsień" },
  { translated: "fat", org: "tłuszcz" },
  { translated: "connective tissue", org: "tkanka łączna" },
  { translated: "organ", org: "organ" },
  { translated: "small intestine", org: "jelito cienkie" },
  { translated: "large intestine", org: "jelito grube" },
  { translated: "liver", org: "wątroba" },
  { translated: "pancreas", org: "trzustka" },
  { translated: "spleen", org: "śledziona" },
  { translated: "peritoneum", org: "otrzewna" },
  { translated: "membrane", org: "błona" },
  { translated: "urinary bladder", org: "pęcherz moczowy" },
  { translated: "rectum", org: "odbytnica" },
  { translated: "pelvis", org: "miednica" },
  { translated: "feverish", org: "gorączkujący" },
  { translated: "carpals", org: "kości nadgarstka" },
  { translated: "clavicle", org: "obojczyk" },
  { translated: "coccyx", org: "kość ogonowa" },
  { translated: "fibula", org: "kość strzałkowa" },
  { translated: "frontal", org: "czołowy" },
  { translated: "humerus", org: "kość ramienna" },
  { translated: "ilium", org: "kość biodrowa" },
  { translated: "ischium", org: "kość kulszowa" },
  { translated: "mandible", org: "żuchwa/szczęka dolna" },
  { translated: "maxilla", org: "kość szczękowa" },
  { translated: "metacarpals", org: "kości śródręcza" },
  { translated: "metatarsals", org: "kości śródstopia" },
  { translated: "occipital", org: "potylica" },
  { translated: "parietal", org: "kość ciemieniowa" },
  { translated: "phalanges", org: "paliczki" },
  { translated: "pubis", org: "kość łonowa" },
  { translated: "radius", org: "kość promieniowa" },
  { translated: "ribs", org: "żebra" },
  { translated: "sacrum", org: "kość krzyżowa" },
  { translated: "scapula", org: "łopatka" },
  { translated: "tarsals", org: "kości stępu" },
  { translated: "tibia", org: "kość piszczelowa" },
  { translated: "ulna", org: "kość łokciowa" },
  { translated: "verteba", org: "kręg" },
  { translated: "zygomatic", org: "jarzmowy" },
  { translated: "The Male Reproductive System", org: "męski układ rozrodczy" },
  {
    translated: "The Female Reproductive System",
    org: "kobiecy układ rozrodczy",
  },
  { translated: "The Urinary System", org: "układ moczowy" },
  { translated: "The Respiratory System", org: "układ oddechowy" },
  { translated: "The Lymphatic System", org: "układ limfatyczny" },
  { translated: "The Digestive System", org: "układ pokarmowy" },
  { translated: "The Cardiovascular System", org: "układ sercowo-naczyniowy" },
  { translated: "The Endocrine System", org: "układ hormonalny" },
  { translated: "The Muscular System", org: "układ mięśniowy" },
  { translated: "The Nervous System", org: "układ nerwowy" },
  { translated: "The Skeletal System", org: "układ szkieletowy" },
  { translated: "The Integumentary System", org: "układ powłokowy" },
  { translated: "affect", org: "atakować (choroba)" },
  { translated: "bend down", org: "schylać się/zginać" },
  { translated: "consist (of)", org: "składać się (z)" },
  { translated: "maintain", org: "utrzymać (na tym samym poziomie)" },
  { translated: "overdo", org: "przesadzić/przesilić się" },
  { translated: "radiate", org: "promieniować" },
  { translated: "stab", org: "wbić/ukłuć" },
  { translated: "combine", org: "łączyć/mieszać" },
  { translated: "contain", org: "zawierać" },
  { translated: "compose", org: "tworzyć" },
  { translated: "notice", org: "zauważać" },
  { translated: "protect (by)", org: "chroniony (przez)" },
  { translated: "bound (by)", org: "związane (przez)" },
  { translated: "divide into", org: "podzielić na coś" },
  { translated: "ovoid", org: "jajowaty" },
  { translated: "dome-shaped", org: "kopulasty" },
  { translated: "inner", org: "wewnętrzny" },
  { translated: "hollow", org: "wgłębienie" },
  { translated: "junction", org: "skrzyżowanie" },
  { translated: "sharp", org: "ostry/przeszywający" },
  { translated: "include", org: "zawierać" },
  { translated: "stabbing pain", org: "przeszywający" },
  { translated: "injury", org: "uraz" },
  { translated: "treating", org: "udzielanie pomocy med." },
  { translated: "sustain", org: "odnosić (obrażenia)" },
  { translated: "laceration", org: "rana szarpana" },
  { translated: "treatment", org: "leczenie" },
  { translated: "require", org: "potrzebować" },
  { translated: "abrasion", org: "otarcie skóry" },
  { translated: "puncture", org: "punkcja" },
  { translated: "strain", org: "nadwyrężyć" },
  { translated: "unharmed", org: "nietknięty" },
  { translated: "severe", org: "poważny" },
  { translated: "trauma", org: "uraz" },
  { translated: "complaint", org: "dolegliwość" },
  { translated: "suspect", org: "podejrzewać" },
  { translated: "movement", org: "ruch" },
  { translated: "experience", org: "doświadczyć" },
  { translated: "identify", org: "rozpoznawać" },
  { translated: "complain", org: "narzekać/skarżyć się" },
  { translated: "extending", org: "rozciągający" },
  { translated: "minor", org: "drobny" },
  { translated: "bruising", org: "stłuczenie" },
  { translated: "significant", org: "znaczny" },
  { translated: "fracture", org: "złamanie" },
  { translated: "evident", org: "widoczny" },
  { translated: "concern", org: "niepokój" },
  { translated: "splint", org: "szyna (unieruchamiająca złamanie)" },
  { translated: "fleshy", org: "mięsisty" },
  { translated: "indication", org: "objaw" },
  { translated: "immobile", org: "unieruchomiony" },
  { translated: "proper", org: "odpowiedni" },
  { translated: "content", org: "zawartość" },
  { translated: "digestion", org: "trawienie" },
  { translated: "feverish", org: "gorączkujący" },
  { translated: "coughing", org: "kaszlenie" },
  { translated: "weight", org: "waga" },
  { translated: "fever", org: "gorączka" },
  { translated: "weak", org: "słaby" },
  { translated: "tired", org: "zmęczony" },
  { translated: "inferiorly", org: "poniższy" },
  { translated: "anteriorly", org: "przednio" },
  { translated: "laterally", org: "bocznie" },
  { translated: "food", org: "pokarm" },
  { translated: "respiratory gases", org: "gazy oddechowe" },
  { translated: "ingestion", org: "przyjmowanie pokarmu" },
  { translated: "digestion", org: "trawienie" },
  { translated: "absorption", org: "wchłanianie" },
  { translated: "irritability", org: "drażliwość" },
  { translated: "stimuli", org: "bodźce" },
  { translated: "nutrition", org: "odżywianie" },
  { translated: "reproduction", org: "reprodukcja" },
  { translated: "propagation", org: "rozmnażanie" },
  { translated: "species", org: "gatunek" },
  { translated: "metabolism", org: "metabolizm" },
  { translated: "growth", org: "wzrost/rośnięcie" },
  { translated: "respiration", org: "oddychanie" },
  { translated: "oxygen", org: "tlen" },
  { translated: "intake", org: "pobór (tlenu)" },
  { translated: "carbon dioxide", org: "dwutlenek węgla" },
  { translated: "excretion", org: "wydalanie" },
];
